public with sharing class ScheduleAnInterview {

    

    private static boolean checkInterviewerAvailability(Id userId)
    {
        return false;
    }
    
    
    public static List<Id> getAllAvailableInterviewers(String startTime, Integer durationInMins, Id eventId)
    {
        return New List<Id>();
    }
    
    public static void scheduleInterview(Id interviewEventCandidate, Id interviewId)
    {
        
    }
    

}